In [13]:


import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn  as sns

In [15]:
df=pd.read_csv("company_esg_financial_dataset.csv")
df.head()

,CompanyID,CompanyName,Industry,Region,Year,Revenue,ProfitMargin,MarketCap,GrowthRate,ESG_Overall,ESG_Environmental,ESG_Social,ESG_Governance,CarbonEmissions,WaterUsage,EnergyConsumption
0,1,Company_1,Retail,Latin America,2015,459.2,6.0,337.5,NaN,57.0,60.7,33.5,76.8,35577.4,17788.7,71154.7
1,1,Company_1,Retail,Latin America,2016,473.8,4.6,366.6,3.2,56.7,58.9,32.8,78.5,37314.7,18657.4,74629.4
2,1,Company_1,Retail,Latin America,2017,564.9,5.2,313.4,19.2,56.5,57.6,34.0,77.8,45006.4,22503.2,90012.9
3,1,Company_1,Retail,Latin America,2018,558.4,4.3,283.0,-1.1,58.0,62.3,33.4,78.3,42650.1,21325.1,85300.2
4,1,Company_1,Retail,Latin America,2019,554.5,4.9,538.1,-0.7,56.6,63.7,30.0,76.1,41799.4,20899.7,83598.8

In [20]:
# 1-Dataset mein missing values aur duplicate records kitne hain?
df.isnull().sum()

CompanyID               0
CompanyName             0
Industry                0
Region                  0
Year                    0
Revenue                 0
ProfitMargin            0
MarketCap               0
GrowthRate           1000
ESG_Overall             0
ESG_Environmental       0
ESG_Social              0
ESG_Governance          0
CarbonEmissions         0
WaterUsage              0
EnergyConsumption       0
dtype: int64

In [21]:
df.duplicated().sum()

np.int64(0)

In [24]:
df["GrowthRate"] =df["GrowthRate"].fillna(True)
df["GrowthRate"] =df["GrowthRate"].fillna("Unknown")

In [28]:
df.dtypes

CompanyID              int64
CompanyName              str
Industry                 str
Region                   str
Year                   int64
Revenue              float64
ProfitMargin         float64
MarketCap            float64
GrowthRate            object
ESG_Overall          float64
ESG_Environmental    float64
ESG_Social           float64
ESG_Governance       float64
CarbonEmissions      float64
WaterUsage           float64
EnergyConsumption    float64
dtype: object

In [29]:
# Industry-wise total revenue aur average profit margin kya hai?
 # total revenue
df["Revenue"].sum()

np.float64(51379356.5)

In [30]:
# average profit margin
df["ProfitMargin"].mean()

np.float64(10.900454545454545)

In [36]:
IWR =df.groupby("Industry")["Revenue"].sum()
IWR

Industry
Consumer Goods     2678226.1
Energy            10453491.8
Finance            7798538.0
Healthcare         6194071.5
Manufacturing      2977921.4
Retail             1881065.6
Technology        16482469.0
Transportation     1449137.7
Utilities          1464435.4
Name: Revenue, dtype: float64

In [37]:
IWPM =df.groupby("Industry")["ProfitMargin"].mean()
IWPM

Industry
Consumer Goods    10.805799
Energy            10.550337
Finance           14.288335
Healthcare        15.446506
Manufacturing      8.489122
Retail             5.487993
Technology        18.798565
Transportation     5.365346
Utilities          9.676381
Name: ProfitMargin, dtype: float64

In [41]:
# Year-wise revenue aur growth rate ka trend kya hai?
YWRPM =df.groupby("Year").agg(ywr=("Revenue","sum"),YWG=("ProfitMargin","sum")).reset_index()
YWRPM

    Year        ywr      YWG
0   2015  3305840.5  10879.1
1   2016  3478708.7  10950.6
2   2017  3705968.1  10989.7
3   2018  3942490.6  10938.8
4   2019  4214272.9  10888.0
5   2020  4494454.9  10782.9
6   2021  4818389.5  10903.8
7   2022  5173362.6  10921.9
8   2023  5599792.1  10931.6
9   2024  6063939.9  10953.2
10  2025  6582136.7  10765.4

In [63]:
# Kaunsi companies ki profitability sabse zyada aur sabse kam hai?
CP= df.groupby("CompanyName")["ProfitMargin"].mean()
print("Lowest:",CP.idxmin(),CP.min())
print("Highest:",CP.idxmax(),CP.max())

Lowest: Company_493 -17.027272727272727
Highest: Company_205 47.53636363636363

In [64]:
# Financial performance aur ESG scores ke beech kya relationship hai?

cols = ["ESG_Overall", "Revenue", "ProfitMargin", "GrowthRate"]

df[cols].corr()

              ESG_Overall   Revenue  ProfitMargin  GrowthRate
ESG_Overall      1.000000  0.148869      0.088006    0.072144
Revenue          0.148869  1.000000      0.132488    0.166512
ProfitMargin     0.088006  0.132488      1.000000    0.058657
GrowthRate       0.072144  0.166512      0.058657    1.000000

In [84]:
# Carbon emissions, water usage aur energy consumption mein kaunsi companies sabse aage hain?
df.columns
CWEC =df.groupby("CompanyName").agg(cc=("CarbonEmissions","sum"),WU=("WaterUsage","sum"),EC=("EnergyConsumption","sum")).reset_index()
CWEC.sort_values("cc", ascending=False).head(5)
CWEC.sort_values("WU", ascending=False).head(5)
CWEC.sort_values("EC", ascending=False).head(5)

     CompanyName           cc           WU            EC
733  Company_759  975938098.3  292781429.5  9.759381e+09
608  Company_646  750668362.9  225200508.9  7.506684e+09
494  Company_543  559408367.1  167822510.1  5.594084e+09
485  Company_535  363545497.2  109063649.2  3.635455e+09
739  Company_764  235433366.2   70630010.0  2.354334e+09

In [94]:
# Kaun-si companies high revenue ke saath high ESG performance bhi achieve kar rahi hain?
df.columns
CRE =df.groupby("CompanyName").agg(RS=("Revenue","sum"),ES=("ESG_Overall","mean")).reset_index()
CRE

      CompanyName        RS         ES
0       Company_1    6433.9  57.209091
1      Company_10  886499.6  66.072727
2     Company_100   13091.5  55.536364
3    Company_1000   33227.7  50.372727
4     Company_101   47159.9  63.972727
..            ...       ...        ...
995   Company_995   23742.2  58.854545
996   Company_996   46874.1  60.790909
997   Company_997    6307.5  64.236364
998   Company_998   17128.6  64.045455
999   Company_999   62772.7  52.709091

[1000 rows x 3 columns]

In [96]:
CR= df.groupby("CompanyName")["Revenue"].mean().sort_values().tail(1)
CR

CompanyName
Company_19    110239.145455
Name: Revenue, dtype: float64

In [98]:
# Kaun-si companies high revenue ke saath high ESG performance bhi achieve kar rahi hain?
CRE = df.groupby("CompanyName").agg(
    Total_Revenue=("Revenue", "sum"),
    ESG_Score=("ESG_Overall", "mean")
).reset_index()
CRE.sort_values(
    ["Total_Revenue", "ESG_Score"],
    ascending=False
).head(10)

     CompanyName  Total_Revenue  ESG_Score
101   Company_19      1212630.6  52.509091
405  Company_463      1123809.6  75.136364
733  Company_759       954049.9  58.845455
608  Company_646       896483.4  80.045455
1     Company_10       886499.6  66.072727
552  Company_596       688908.7  88.527273
28   Company_123       678047.2  60.363636
736  Company_761       650576.2  57.836364
285  Company_355       585863.1  83.309091
128  Company_213       585776.1  74.418182

In [104]:
import pandas as pd
from sqlalchemy import create_engine
from sqlalchemy.engine import URL

# 1. CSV dataset
df =pd.read_csv("company_esg_financial_dataset.csv")


# 2. MySQL connection
connection_url = URL.create(
    drivername="mysql+pymysql",
    username="root",
    password="shivam@1734",
    host="localhost",
    port=3306,
    database="FinanceESG_db"
)

engine = create_engine(connection_url)

print("MySQL connected successfully")

# 3. Upload Python DataFrame → MySQL table
df.to_sql(
    name="FinanceESGtable",
    con=engine,
    if_exists="replace",
    index=False
)

print("Dataset uploaded successfully");

# # 4. Read table back from MySQL
# df_sql = pd.read_sql("SELECT * FROM  FinanceESGtable",engine)

#  df_sql.head()

MySQL connected successfully

InvalidRequestError: Could not reflect: requested table(s) not available in Engine(mysql+pymysql://root:***@localhost:3306/FinanceESG_db): (FinanceESGtable)